Add structure to the code
musec/fmvparse pull request #1
Opened 2022-01-20 20:31 UTC by arastoob

This will help us have a structural code. The main boxes are organized in their own structures and later we can add more functionalities to them, e.g., add some functions to the `Movie` structure to get the corresponding video frame of a specific time period.

2022-01-24 15:22 UTC, sdharar commented on src/header.rs
> +    pub fn header(data: &[u8], start: usize) -> Result<Self, Error> {
warning: constructor `header` has the same name as the type
  --> src\header.rs:17:5
   |
17 | /     pub fn header(data: &[u8], start: usize) -> Result<Self, Error> {
18 | |         // the first 8 bytes includes the atom size and its name
19 | |         // The size is the entire size of the box, including the size and type header, fields, and all contained boxes.
20 | |         let size = BigEndian::read_u32(&data[0..4]) as usize;
...  |
23 | |         Ok(Self { name, size, start })
24 | |     }
   | |_____^
   |
   = note: `#[warn(clippy::self_named_constructors)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#self_named_constructors

2022-01-24 15:23 UTC, sdharar commented on src/boxes/file_type.rs
> +    data: Vec<u8>,
warning: field is never read: `data`
  --> src\boxes\file_type.rs:13:5
   |
13 |     data: Vec<u8>,
   |     ^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

2022-01-24 15:23 UTC, sdharar commented on src/boxes/media_data.rs
> +    data: Vec<u8>,
warning: field is never read: `data`
  --> src\boxes\media_data.rs:13:5
   |
13 |     data: Vec<u8>,

2022-01-24 15:24 UTC, sdharar commented on src/boxes/mp4_box.rs
> +    fn fields(&self) -> Option<Vec<&Box<dyn Mp4Box>>>;
warning: you seem to be trying to use `&Box<T>`. Consider using just `&T`
  --> src\boxes\mp4_box.rs:31:36
   |
31 |     fn fields(&self) -> Option<Vec<&Box<dyn Mp4Box>>>;
   |                                    ^^^^^^^^^^^^^^^^ help: try: `&dyn Mp4Box`
   |
   = note: `#[warn(clippy::borrowed_box)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#borrowed_box

2022-01-24 15:25 UTC, sdharar commented on src/boxes/mp4_box.rs
> +        if internals.is_some() {
warning: called `unwrap` on `internals` after checking its variant with `is_some`
  --> src\boxes\mp4_box.rs:51:29
   |
50 |         if internals.is_some() {
   |         ---------------------- help: try: `if let Some(..) = internals`
51 |             for internal in internals.unwrap() {
   |                             ^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(clippy::unnecessary_unwrap)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_unwrap

2022-01-24 15:25 UTC, sdharar commented on src/bin/main.rs
> +    verbose: bool,
warning: field is never read: `verbose`
  --> src\bin\main.rs:16:5
   |
16 |     verbose: bool,
   |     ^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

2022-01-24 15:30 UTC, sdharar requested changes
Dr. @arastoob => The structure of the code has improved a lot, and it appears to generate the expected results. Upon running some tests, I have stumbled upon some changes that have been added as comments.

If you think the code requires changes based on my comments, perhaps those changes can be made before committing this PR.

2022-01-24 20:52 UTC, arastoob commented
> 
What comments do you mean? If you mean `reader` and `boxes_old` files, they are your file and I thought we might need it. If you think that the new code has covered what is inside those files, we can remove them?

2022-01-25 01:38 UTC, sdharar commented
> 
No, I meant the comments that I added on your code. Yes, the new code does pretty much outputs the same thing that older code did, in addition to one more layer further down in track/moov atoms but its more structured. The ftype atom needs more further layer to be implemented. Perhaps we can take some implementations from the older code for ftype atom. What do you think?

2022-01-26 13:00 UTC, arastoob commented
> > 
> 
> No, I meant the comments that I added on your code. Yes, the new code does pretty much outputs the same thing that older code did, in addition to one more layer further down in track/moov atoms but its more structured. The ftype atom needs more further layer to be implemented. Perhaps we can take some implementations from the older code for ftype atom. What do you think?

So where can I see the comments?

2022-01-26 15:57 UTC, sdharar commented
> > > 
> > 
> > 
> > No, I meant the comments that I added on your code. Yes, the new code does pretty much outputs the same thing that older code did, in addition to one more layer further down in track/moov atoms but its more structured. The ftype atom needs more further layer to be implemented. Perhaps we can take some implementations from the older code for ftype atom. What do you think?
> 
> So where can I see the comments? and yes, please go ahead and add your code to ftype.

I added suggestions I received from clippy on this webpage, which I guess you already have rectified.

2022-01-26 16:47 UTC, arastoob commented
> > > > 
> > > 
> > > 
> > > No, I meant the comments that I added on your code. Yes, the new code does pretty much outputs the same thing that older code did, in addition to one more layer further down in track/moov atoms but its more structured. The ftype atom needs more further layer to be implemented. Perhaps we can take some implementations from the older code for ftype atom. What do you think?
> > 
> > 
> > So where can I see the comments? and yes, please go ahead and add your code to ftype.
> 
> I added suggestions I received from clippy on this webpage, which I guess you already have rectified.

Yes, I have resolved those comments. Sorry, I thought that you have made some comments inside the code. So, I can merge the code into master.

2022-01-26 16:54 UTC, merged